Update Loyalty API to deploy the Account CloudWatchRole that is required
aws-samples/aws-serverless-airline-booking pull request #130
Opened 2020-09-25 16:15 UTC by deldrid1

*Issue #, if available:*
#128

*Description of changes:*
I ran into the same issue described in #128.  

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-account.html holds the answer to fix this programatically and in a region agnostic way.

FYI - There seems to be some fragility with the order of operations here:
![image](https://user-images.githubusercontent.com/583660/94289397-a9278100-ff26-11ea-8312-eab8d7b04e62.png)

I haven't tested on a clean AWS account, but given that Payments API deploys clean, I think this fix will work (I'm not a SAM expert and am coming from another cloud provider so troubleshooting this has been quite the learning experience!)

Note: if you're in the state described in #128, you will need to manually go into the CloudFormation Console and delete the stack stuck in `ROLLBACK_COMPLETE` or you will get an error like this one: 
  - ![image](https://user-images.githubusercontent.com/583660/94287146-f0604280-ff23-11ea-83c7-bc19e9d44d73.png)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-26 09:10 UTC, heitorlessa commented
Hey Austin - Thanks for taking the time to do this.

I'll go through this during the week, and circle back here :)

I was nearly sure this was in place already. I'll do some digging in the history to double check before I make some minor suggestions here

2020-09-27 19:06 UTC, heitorlessa commented
Just remember why this wasn't added now - API Gateway only allows a single IAM Role, so if customers were to deploy this in their accounts it can override a previously setup IAM Role in their accounts (need to double check the behaviour).

Regardless, we should provide these resources commented for educational purposes, and remove the attempt to have Logs enabled as it currently stands to prevent build failures.

Could you allow me to make changes in your fork so I can change the naming convention, and add some info there?

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

2020-09-27 19:43 UTC, deldrid1 commented
Looks checked to me? I didn’t make any changes

2020-09-27 19:52 UTC, heitorlessa commented
Great, I’ll push changes this week and ask for your review

On Sun, 27 Sep 2020 at 21:43, Austin Eldridge <notifications@github.com>
wrote:

>
>
>
> Looks checked to me? I didn’t make any changes
>
>
>
>
>
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/aws-samples/aws-serverless-airline-booking/pull/130#issuecomment-699679381>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZPQBD5O2K5WFBF7MLNFCTSH6IWRANCNFSM4RZXETHQ>
> .
>
>
>
>

2020-10-02 14:42 UTC, heitorlessa commented
I'm getting access denied when trying to push to your fork/branch w.r.t this PR - I've created a patch file that you can apply, so I can merge it. 

https://gist.github.com/heitorlessa/515584f84d40208d6e4c329d78fbb691

2020-10-02 14:42 UTC, heitorlessa requested changes
Apply patch (`git apply <patch>`): https://gist.github.com/heitorlessa/515584f84d40208d6e4c329d78fbb691

2020-10-05 13:31 UTC, deldrid1 commented
Not sure what is going on with the permissions...
![image](https://user-images.githubusercontent.com/583660/95085432-37e98a00-06ed-11eb-85b5-9e19cfb86f42.png)


I've applied the patch.  From my perspective this is good to go, although it will be a breaking change for folks that blindly pull with a working repo - logs that were there will no longer be configured after a fresh deply so you may want to think about that in terms of versioning.  

I would also recommend some additional README content somewhere about the ability to enable this logging and why its useful, but its your repo so I'll leave it to you to decide if that is useful or not!

2020-10-09 10:03 UTC, heitorlessa commented
Appreciate the changes and comments @deldrid1, truly. As for the docs, I'll do this separately, specifically the [decision log](https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/src/backend/loyalty/README.md#decisions-log) section in Loyalty to describe why that was necessary. 

Significant changes to the project per se are also documented here: https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/docs/decision_log.md

After re:Invent, I'll get back to this to tackle some major operations, testing, etc. documented in the Boards/Issues.

2020-10-09 10:03 UTC, heitorlessa approved these changes

2020-10-09 10:03 UTC, merged